apiVersion: v1
kind: Service
metadata:
  name: simple-jwt-api
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: simple-jwt-api
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-jwt-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-jwt-api
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: simple-jwt-api
    spec:
      containers:
        - image: CONTAINER_IMAGE
          name: simple-jwt-api
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
